### ISSUE TITLE
Consider using RCStream instead of irc.wikimedia.org

### ISSUE THREAD

**Issue by Krinkle** [DamianZaremba/cluebotng#1]
It's currently not yet publicly advertised, but would you be interested in becoming an early adopter of [RCStream](https://wikitech.wikimedia.org/wiki/RCStream)?

It currently uses the Socket.IO v0.9 protocol (we'll soon upgrade to the incompatible 1.0 protocol), but other than that it is stable enough to start looking into. It certainly has better uptime, network reliability and operations support (multiple servers, load balancer) than e.g. the legacy IRC feed.

It should be easier for applications like yours to consume the JSON stream than to decode the colourful IRC feed (though naturally you already have decoding for that in place). It'd be cool to have ClueBot NG as an early adopter. Contrary to the IRC feed, RCStream is much more extendable. So do let us know if there's anything we can do to make your life easier (e.g. exposing more data in the stream, or via the API).

**Comment by benapetr** [comment]
Hi,

Just out of curiosity, huggle and wm-bot are both already indirectly using RCStream (through [[wikitech:XmlRcs]] because JSON and websocket.IO is kind of overkill for both).

I already found it stable enough, not sure how complex would it be for cluebot to use it. Its core is C++, but there is a number of wrappers so it probably shouldn't be a big deal.

**Comment by benapetr** [comment]
BTW: we will soon upgrade to 1.0 protocol - are you aware that for example, most common python library for websocket.IO doesn't support this yet? If you do that all python tools that use RCStream will break.

**Comment by DamianZaremba** [comment]
The part which deals with stream processing is all in PHP - only the scoring engine is in C++. If I get chance I'll take a look at this - probably making a new interface with the 2 implementations.

The main irc processing is triggered from https://github.com/DamianZaremba/cluebotng/blob/master/bot/feed_functions.php, however there is a lot of notification and configuration logic tied into it... so we can't just "turn off irc".

**Comment by LandonPowell** [comment]
You might want to consider just using WebSockets instead of bloating up your webapp with Socket.io.
https://seafour.club/ Create yourself a RCStream room on SeaFour, lol.

**Comment by Krinkle** [comment]
I'm closing this as I no longer recommend new adoption of RCStream. While RCStream is certainly easier to process than IRC, ClueBotNG already did the groundwork for that. At the moment I would say that IRC and RCStream are about equally stable (favouring toward the less-experimental irc.wikimedia.org).

The Analytics team is working on a more stable and more maintainable event stream interface, of which recentchanges will also be a part. Once ready, RCStream will likely be deprecated and remain in its experimental form until it is shutdown. The IRC interface will remain for longer.

<https://phabricator.wikimedia.org/T130651>
