### ISSUE TITLE
error upon attempting to run

### ISSUE THREAD

**Issue by h4x0r888** [DamianZaremba/cluebotng#11]
terminate called after throwing an instance of 'libconfig::FileIOException'
  what():  FileIOException
Aborted (core dumped)

**Comment by DamianZaremba** [comment]
This most likely means you don't have a valid cluebotng.conf, by default it's expected to live in conf/.

Try running from the main directory with https://github.com/DamianZaremba/cluebotng/tree/master/conf present, or point it to another place using `-c`

**Comment by h4x0r888** [comment]
thanks!
