### ISSUE TITLE
General query about the bot

### ISSUE THREAD

**Issue by SushilShrestha** [DamianZaremba/cluebotng#12]
Hi,
It is not exactly an issue but I am looking for the original research paper for Cluebot_ng. 
[ClueBot_NG wiki](https://en.wikipedia.org/wiki/Wikipedia:Bots/Requests_for_approval/ClueBot_NG) has [broken link](http://98.222.57.24/Cluebot-NG.pdf) for the original paper and google & webarchive search have no results. So just wanted to ask if somebody has the paper. Just curious about how the bot works. 
Thanks

**Comment by Cobi** [comment]
Ahh, yes, that ancient IP address.  It's moved to S3 for more proper long term storage: http://files.cobi.ninja/Cluebot-NG.pdf

**Comment by legoktm** [comment]
Is the paper freely licensed? Could it be uploaded to Commons?

**Comment by SushilShrestha** [comment]
Thanks @Cobi
