### ISSUE TITLE
crontab is using dysfunctional syntax

### ISSUE THREAD

**Issue by scfc** [DamianZaremba/cluebotng#2]
The `crontab` read for example:

```
* * * * *   /usr/bin/jsub -N cron-tools.cluebot-cbng_bot -e $HOME/logs/cron.err -o $HOME/logs/cron.out -once -quiet /usr/bin/qstat 2>&1 | /bin/grep -q cbng_bot || sleep 20 && /usr/bin/jsub -once -continuous -e /dev/null -o /dev/null -N cbng_bot -mem 6G $HOME/cluebotng/bin/run_bot.sh &> /dev/null
```

This doesn't work on multiple levels:

1. `jsub -e […] qstat` will never return anything on `stdout` (it just schedules the job, it does not run it), so the `grep` will always fail.
2. Even if the `grep` was meaningful, the Boolean logic would always cause the execution of the second `jsub`: `false && sleep 1 || echo Always executed`.
3. The whole "test if a job with the same name is already running" is already contained in the `-once` option (or `jstart`).
4. Instead of running multiple `cron` jobs every minute, you should list the continuous jobs in `~/.bigbrotherrc` which will ensure that they will be restarted by `bigbrother` if needed.

I have removed the obsolete entry `webservice` from `~/.bigbrotherrc` and instead added:

```
# Cluebot NG
jstart -N cbng_bot   -e /dev/null -o /dev/null -mem 6G /data/project/cluebot/cluebotng/bin/run_bot.sh &> /dev/null
jstart -N cbng_relay -e /dev/null -o /dev/null -mem 6G /data/project/cluebot/cluebotng/bin/run_relay.sh &> /dev/null
jstart -N cbng_redis -e /dev/null -o /dev/null -mem 6G /data/project/cluebot/cluebotng/bin/run_redis.sh &> /dev/null
jstart -N cbng_core  -e /dev/null -o /dev/null -mem 6G /data/project/cluebot/cluebotng/bin/run_core.sh &> /dev/null

# Cluebot3
jstart -N cluebot3   -e /dev/null -o /dev/null -mem 12G php -f /data/project/cluebot/cluebot3/cluebot3.php
```

I have removed the corresponding lines from the enabled `crontab`.  I have saved the old `crontab` in `~/crontab.bak` and the new `crontab` (also) in `~/crontab.new`.

I would submit a pull request for `tools-crontab`, but I don't know how you want to deploy `~/.bigbrotherrc` from fabric.

**Comment by DamianZaremba** [comment]
The cron syntax is a hangover from before crons where run on SGE - at that time, the output was inline so the conditional 'sort of' worked (aside from the right half not being in braces, so both sides are executed no matter what). The -once should have covered it, but for some reason you could get multiple processes running.

I've moved the lines over into .bigbrotherrc (it didn't exist when the crons where added) so things should be in a more sane state.
