### ISSUE TITLE
Minor question 

### ISSUE THREAD

**Issue by MFernflower** [DamianZaremba/cluebotng#7]
In the function addChainLink() in Main.cpp - wouldn't it be more efficient to use a fullblown switch statement instead of the elseif chain?

**Comment by jcarter-okta** [comment]
C++ doesn't really like switch statements with strings.  Also, a switch statement is only more effective when the compiler can build a jump table, which is not really feasible with strings.

**Comment by MFernflower** [comment]
Fair enough. Ill close the issue later today
