### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AsdfMovie12345** [DamianZaremba/cluebotng#8]
Error

make -C src all
make[1]: Entering directory '/home/<<name>>/cluebotng/src'
g++ -g -O2 main.cpp --static -lexpat -ldb_cxx -liconv -lfann -lconfig++ -lboost_thread -lboost_system -lm -lmatheval -lfl -Bdynamic -lpthread -ocluebotng
main.cpp: In function ‘void addConfigChain(WPCluebot::EditProcessChain&, libconfig::Setting&, libconfig::Setting&, libconfig::Setting&)’:
main.cpp:289:41: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}
’)
             Setting & linkcfg = linkcfgs[chainelname];
                                         ^
In file included from main.cpp:25:0:
/usr/local/include/libconfig.h++:223:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](const char*) const
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘const char*’
/usr/local/include/libconfig.h++:224:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](int) const
   Setting & operator[](int index) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:224:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘int’
main.cpp:294:48: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}
’)
             addConfigChain(procchain, chaincfgs[chainelname], linkcfgs, chaincfgs);
                                                ^
In file included from main.cpp:25:0:
/usr/local/include/libconfig.h++:223:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](const char*) const
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘const char*’
/usr/local/include/libconfig.h++:224:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](int) const
   Setting & operator[](int index) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:224:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘int’
main.cpp: In function ‘int main(int, char**)’:
main.cpp:348:42: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}
’)
     Setting & rootchaincfg = configchains[chainname];
                                          ^
In file included from main.cpp:25:0:
/usr/local/include/libconfig.h++:223:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](const char*) const
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘const char*’
/usr/local/include/libconfig.h++:224:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](int) const
   Setting & operator[](int index) const;
             ^~~~~~~~
/usr/local/include/libconfig.h++:224:13: note:   no known conversion for argument 1 from ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’ to 
‘int’
Makefile:6: recipe for target 'cluebotng' failed
make[1]: *** [cluebotng] Error 1
make[1]: Leaving directory '/home/<<name>>/cluebotng/src'
Makefile:4: recipe for target 'bins' failed
make: *** [bins] Error 2

**Comment by DamianZaremba** [comment]
Thanks for the report.

2 second reply; it requires very specific versions of dependencies.

Apparently, the Travis build is broken though, so I'll look at fixing that this week when I have a chance (https://travis-ci.org/DamianZaremba/cluebotng).

The Dockerfile appears to build correctly, so you could use that as a good starting point to run it locally (pretty much is just downloading specific versions of things).

Could you provide the versions of deps you are using and I'll have a poke around to see if there's any chance of getting things to compile?

**Comment by AsdfMovie12345** [comment]
I installed the correct versions and got it to compile. How do I configure and launch the bot?
